import { ThemeProvider } from '@/components/ui/theme-provider'
import '../globals.css'
import Nav from '@/components/layout/home2/navigation/Nav'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className='overflow-x-hidden bg-gray-900'>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Nav />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}